server:
  port: 9527
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: landingpage_server_route #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:22001          #匹配后提供服务的路由地址
          uri: lb://landingpage-server-provider #匹配后提供服务的路由地址
          predicates:
            - Path=/api-landingpage/**         # 断言，路径相匹配的进行路由
          filters:
            - StripPrefix=1

        - id: user_server_route #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:22001          #匹配后提供服务的路由地址
          uri: lb://user-server-provider #匹配后提供服务的路由地址
          predicates:
            - Path=/user/**         # 断言，路径相匹配的进行路由
          filters:
            - StripPrefix=1

eureka:
  client:
    #register-with-eureka: true #是否向注册中心注册自己 默认true
    #fetchRegistry: true #是否从注册中心抓取已有的注册信息 默认true，集群必须设置为true
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
    prefer-ip-address: true  #访问路径可以显示IP地址

logging:
  config: classpath:logback/logback.xml
