server:
  port: 22002
spring:
  application:
    name: landingpage-server-provider
  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/landing_page?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  redis:
    host: 192.168.88.103
    port: 6379
    password: Zhc123..
    timeout: 3000
    database: 0
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 1ms
        max-idle: 4
        # 连接池中的最小空闲连接
        min-idle: 0
logging:
  config: classpath:logback/logback.xml
eureka:
  client:
    #register-with-eureka: true #是否向注册中心注册自己 默认true
    #fetchRegistry: true #是否从注册中心抓取已有的注册信息 默认true，集群必须设置为true
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
    prefer-ip-address: true  #访问路径可以显示IP地址
    #Eureka客户端向服务端发送心跳的时间间隔，单位为秒(默认是30秒)
    #lease-renewal-interval-in-seconds: 1
    #Eureka服务端在收到最后一次心跳后等待时间上限，单位为秒(默认是90秒)，超时将剔除服务
    #lease-expiration-duration-in-seconds: 2
feign:
  hystrix:
    enabled: true

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000

hystrix:
  threadpool:
    default:
      coreSize: 10
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1500
      circuitBreaker:
        requestVolumeThreshold: 20
      fallback:
        isolation:
          semaphore:
            maxConcurrentRequests: 5
#    IUserRemote#userTestasdfsadfsd():
#      execution:
#        isolation:
#          strategy: SEMAPHORE
#          semaphore:
#            maxConcurrentRequests: 2
#    OrderServiceFeignClient#orders():
#      execution:
#        isolation:
#          strategy: SEMAPHORE
#          semaphore:
#            maxConcurrentRequests: 10
#    OrderServiceFeignClient#insert():
#      execution:
#        isolation:
#          strategy: THREAD

